"""init

Revision ID: 4c2077bb6f14
Revises: 
Create Date: 2025-09-04 11:21:57.098194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c2077bb6f14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('author_avatars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_uuid', mysql.CHAR(length=36), nullable=False, comment='用户UUID'),
    sa.Column('base64', mysql.MEDIUMTEXT(), nullable=False, comment='Base64编码的头像'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=False, comment='人设UUID'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='浏览量'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='人设名称'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='人设标题'),
    sa.Column('avatar', sa.Text(), nullable=True, comment='头像URL'),
    sa.Column('content', sa.Text(), nullable=True, comment='人设内容'),
    sa.Column('description', sa.Text(), nullable=True, comment='人设描述'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='标签列表，逗号分隔'),
    sa.Column('ext_data', sa.JSON(), nullable=True, comment='扩展数据（JSON格式）'),
    sa.Column('author_uuid', mysql.CHAR(length=36), nullable=False, comment='作者UUID'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('persona_avatars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('persona_uuid', mysql.CHAR(length=36), nullable=False, comment='人设UUID'),
    sa.Column('base64', mysql.MEDIUMTEXT(), nullable=False, comment='Base64编码的头像'),
    sa.ForeignKeyConstraint(['persona_uuid'], ['personas.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona_avatars')
    op.drop_table('personas')
    op.drop_table('author_avatars')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
