"""Update AuthorAvatar base64 to MEDIUMTEXT

Revision ID: a879c9658b3e
Revises: eb5ef0332001
Create Date: 2025-09-02 13:24:43.028223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a879c9658b3e'
down_revision: Union[str, None] = 'eb5ef0332001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author_avatars', 'base64',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='Base64编码的头像',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author_avatars', 'base64',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_comment='Base64编码的头像',
               existing_nullable=False)
    # ### end Alembic commands ###
